name: CI — pytest + coverage

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            # - name: Set up Python
            #   uses: actions/setup-python@v4
            #   with:
            #       python-version: "3.13"

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install dependencies
              run: |
                  uv sync --extra dev
                  if ! command -v ffmpeg &> /dev/null; then
                    sudo apt-get update
                    sudo apt-get install -y ffmpeg
                  fi
            - name: create example configuration
              run: |
                  cp -v config.yml.template config.yml

            - name: Run tests with coverage
              run: |
                  uv run pytest -v

            - name: Upload coverage to GitHub Actions summary
              if: always()
              uses: actions/upload-artifact@v7
              with:
                  name: coverage-report
                  path: coverage.xml
